# Generated by Django 4.0.3 on 2023-12-28 06:47

from django.db import migrations, models
import pybo.models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_question_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='filename',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=pybo.models.get_file_path),
        ),
    ]
